### PR TITLE
Stop counting unassigned for badge number if unassigned inbox is disabled

### PR DESCRIPTION
**Pull request by jasonn85**
... in the user's settings (and if assignment is enabled)

anigif_enhanced-buzz-12347-1366729320-1

### CODE REVIEW

**Comment by jasonn85** [comment]
Keeping this WIP until I have a chance to look it over again tomorrow, especially on services with assignment disabled.

**Comment by jasonn85** [comment]
Good to go now.

**Comment by jasonn85** [comment]
Temporary comment using the word WIP

**Comment by tjtedeschi** [comment]
RE: the gif - What a sad kid's movie

**Pull request merged**
