### PR TITLE
ZIN-2057: "undefined is typing a message.." seen when viewing a convo

### PR DESCRIPTION
**Pull request by svdz**
It looks weirdly why this field was changed on the server. I am pretty sure this won't was done by occasion.

### CODE REVIEW

**Comment by jasonn85** [comment]
This is a regression on the server end, right? This fix does not belong on our end.

**Comment by jasonn85** [comment]
I commented in Jira and am waiting for a response, but I really don't think this belongs on us.

**Comment by svdz** [comment]
I said from the beginning that this is the server issue. But nobody heard me.

**Comment by jasonn85** [comment]
Closing, expecting a server-side fix.

**Pull request closed without merging**
